version: '2'
services:
  nexus3:
    image: jalexoid/sonatype-nexus:3.1.0-04
    ports:
     - "8081:8081"
    volumes:
      - data:/data
    environment:
	MAX_HEAP: 1024m
	MIN_HEAP: 512m
	JAVA_OPTS: -server -Djava.net.preferIPv4Stack=true
